artconfig:
  mainPath: "./"
  forecastMode: 0
  daysPerRun: 1
  refDayToStart: 0
  numberOfRuns: 1
  runPreProcessing: false
  runMohid: true
  runPostProcessing: false
  startDate: "2019 06 01 12 30 05"
  endDate: "2019 06 02 12 30 05"
mohid:
  mpi:
    enable: 0
    numDomains: 0
    exePath: "../"
    keepDecomposedFiles: 0
    ddcParserNumProcessors: 0
    ddcComposerNumProcessors: 0
    joinerVersion: 1
  maxTime: 40000
  outputFile: 0
  outputPath: "../"
  exePath: .
  models:
    model1:
      name: "modelname"
      path: "modelpath"
      mpiProcessors: 2
      obc:
        enable: 0
        fromMyOcean: 0
        simulatedDays: 0
      meteo:
        enable: 0
        modelName: "meteoModelName"
        simulatedDays: 420
        fileNameFromModel: 1
        workPath: "./"
      gridFile: "blabla.dat"
      runId: 1
      DT: 1
      backupPath: "../path/to/backup"
      storagePath: "../path/to/storage"
      hasWaterProperties: 1
      hasInterfaceSedimentWater: 0
      hasSurfaceHDF: 1
      hasGOTM: 1
      hasOutputWindow: 0
      hasSolutionFromFile: 1




