artconfig:
  mainPath: "./"
  classicMode: 0
  forecastMode: 1
  daysPerRun: 1
  refDayToStart: 0
  numberOfRuns: 2
  runPreProcessing: false
  runMohid: true
  runPostProcessing: false
  startDate: "2019 04 26 00 00 00"
  endDate: "2019 04 28 00 00 00"
mohid:
  mpi:
    enable: 1
    numDomains: 3
    exePath: "/usr/bin/mpirun"
    keepDecomposedFiles: 0
    ddcParserNumProcessors: 0
    ddcComposerNumProcessors: 0
    joinerVersion: 1
  maxTime: 40000
  outputFile: 0
  outputPath: "../"
  exePath: "MOHIDWaterMPI.exe"
  models:
    model1:
      name: "MARPOCS_Marrocos_level1"
      path: "MARPOCS_Marrocos_level1/"
      mpiProcessors: 1
      obc:
        enable: 1
        simulatedDays: 1
        workPath: "/ekman1raid/Marpocs_4km/Level2/Results_HDF//"
      meteo:
        enable: 1
        meteo1:
          modelName: "Gfs_0p25"
          simulatedDays: 1
          fileNameFromModel: 1
          workPath: "./"
      gridFile: "GeneralData/Bathymetry/Janela_Marrocos_2km.dat"
      runId: 1
      DT: 90
      backupPath: "../Backup/Level1"
      storagePath: "../Backup/Level1"
      hasWaterProperties: 1
      hasInterfaceSedimentWater: 0
      hasSurfaceHDF: 0
      hasGOTM: 0
      hasOutputWindow: 0
      hasSolutionFromFile: 1
    model2:
      name: "MARPOCS_Marrocos_level2"
      path: "MARPOCS_Marrocos_level1/MARPOCS_Marrocos_level2//"
      mpiProcessors: 1
      obc:
        enable: 0
        simulatedDays: 1
        workPath: "/ekman1raid/Marpocs_4km/Level2/Results_HDF//"
      meteo:
        enable: 1
        meteo1:
          modelName: "Gfs_0p25"
          simulatedDays: 1
          fileNameFromModel: 1
          workPath: "./"
      gridFile: "Agadir_smooth_8celulas_v01.dat"
      runId: 1
      DT: 30
      backupPath: "../Backup/Level2"
      storagePath: "../Storage/Level2"
      hasWaterProperties: 1
      hasInterfaceSedimentWater: 0
      hasSurfaceHDF: 1
      hasGOTM: 1
      hasOutputWindow: 0
      hasSolutionFromFile: 0



